# hugo server --minify --themesDir ... --baseURL=http://0.0.0.0:1313/theme/hugo-book/

baseURL = 'https://ece385docs.web.illinois.edu/'
title = 'ECE385 Docs'
theme = 'hugo-book'
language-code="en-US"

# Book configuration
disablePathToLower = true
enableGitInfo = true

# Needed for mermaid/katex shortcodes
[markup]
[markup.goldmark.renderer]
  unsafe = true

[markup.tableOfContents]
  startLevel = 1

[params]
  BookTheme = 'auto'
  BookToC = true
  BookSection = 'docs'
  BookRepo = 'https://github.com/pradyungn/ECE385-systemverilog-docs'
  BookDateFormat = 'January 2, 2006'
  BookSearch = true
  BookComments = false

  BookPortableLinks = false
  BookServiceWorker = false
  BookTranslatedOnly = false
